version: "3.9"

services:
  web:
    build: .
    container_name: ai_agent
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: memory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

volumes:
  postgres_data:
